// Top level macros
#define EMBER_AF_DEVICE_NAME "ash-v3-test-app"

#define EMBER_APPLICATION_HAS_COUNTER_HANDLER
#define EMBER_APPLICATION_HAS_WAKEUP_HANDLER
#define EMBER_APPLICATION_HAS_BINARY_COMMAND_INTERPRETER
#define EMBER_APPLICATION_HAS_ASH_STATUS_HANDLER
#define EMBER_APPLICATION_HAS_APP_NAME
#define EMBER_APPLICATION_USES_SOFTWARE_FLOW_CONTROL
#define EMBER_HEAP_SIZE 8000
#define EMBER_ASH_V3_TEST_APP
